version: 2.1

commands:
  inspect:
    steps:
      - run: |
          go version
          node -v
          npm -v

jobs:
  deps:
    parameters:
      img:
        type: string
    machine:
      image: << parameters.img >>
    resource_class: medium
    steps:
      - inspect
 
workflows:
  main:
    jobs:
      - deps:
          matrix:
            parameters:
              img:
                - "ubuntu-2204:2022.07.1"
                - "ubuntu-2004:2022.07.1"

