version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: large
    steps:
      - run: cat /home/circleci/.circlerc
      - run:
          name: test echo
          command: |
            echo About to pull Cypress docker image > /tmp/test.log
      - run:
          name: test jq
          command: |
            echo '{"v": "13.6.3"}' >> results.json
            echo "export VERSION=$(jq -r '.v' results.json)" >> $BASH_ENV
      - run:
          name: test docker pull
          command: |
            echo "Cypress version is $VERSION"
            # NOTE: i think this should be the below, for safety:
            #  docker pull "cypress/included:${VERSION}"
            docker pull cypress/included:"$VERSION"
