version: 2.1

jobs:
  pull:
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - run:
          name: test
          shell: /bin/bash -exo pipefail
          command: |
            echo About to pull a Docker image
            echo About to pull a Docker image > /tmp/debug.log
            VERSION="13.7.1"
            echo "Cypress version is $VERSION"
            docker pull cypress/included:$VERSION
            echo pulled cypress/included:$VERSION >> /tmp/debug.log
 
workflows:
  mar-29-2024:
    jobs:
      - pull

