version: 2.1

commands:
  install-helm:
    steps:
      - run:
          name: install Helm
          command: |
            curl -o helm-v3.13.3.tar.gz https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
            tar -zxvf helm-v3.13.3.tar.gz
            sudo mv ./linux-amd64/helm /usr/local/go/bin
      - run:
          name: inspect Helm
          command: |
            which helm
            helm version
  upgrade_ssh:
    steps:
      - checkout
      - run:
          name: Install OpenSSH 8.9
          command: |
            sudo apt-get update
            mkdir ~/tempdownload; 
            cd ~/tempdownload; 
            wget https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-8.9p1.tar.gz; 
            tar zxvf openssh-8.9p1.tar.gz; 
            cd openssh-8.9p1 && ./configure && make && sudo make install
            # echo "export PATH='~/tempdownload/openssh-8.9p1:$PATH'" > $BASH_ENV
      - run: |
          which ssh
          ssh -V
          ls /home/circleci/.ssh/
  inspect:
    steps:
      - run: |
          ssh -V
      - run: |
          openssl version
#       - run: |
#           cat /home/circleci/.ssh/config
#           sed 's/IdentitiesOnly no/IdentitiesOnly yes/1' /home/circleci/.ssh/config
          
#           sed 's/IdentitiesOnly no/IdentitiesOnly yes/1' /home/circleci/.ssh/config > /home/circleci/.ssh/config
#           cat /home/circleci/.ssh/config
#       - run: |
#           # check SSH config validity
#           sshd -t
      - run: |
          docker version
          docker info
      - run: |
          docker-compose version
      - run: |
          lsb_release -a
          uname -r
  install-sfdx:
    steps:
      - run: |
          node -v
          npm -v
      - run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
          ./sfdx/install
          
          sfdx commands

jobs:
  default:
    machine: true
    steps:
      - inspect
      - install-sfdx
  test-path:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - run:
          command: |
            wget https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64.tar.gz -O - | tar xz && mv yq_linux_amd64 ~/bin/yq
            pwd
            echo "---------------"
            ls -laH $HOME/bin
            
            PATH=$HOME/bin:$PATH
            echo "export PATH=$PATH" >> $BASH_ENV
      - run:
          command: printenv PATH
  build:
    parameters:
      img:
        type: string
    machine:
      image: << parameters.img >>
    resource_class: medium
    steps:
      - install-helm
 
workflows:
  jul-27-2023:
    jobs:
      - build:
          matrix:
            parameters:
              img:
                # See https://circleci.com/developer/machine/image/ubuntu-2004#image-tags
                # - "ubuntu-2004:202008-01"
                # - "ubuntu-2004:202104-01"
                # - "ubuntu-2004:202107-02"
                # - "ubuntu-2004:2023.04.2"
                - "ubuntu-2004:2023.07.1"

