version: 2.1

jobs:
  test-sudo:
    parameters:
      img:
        type: string
    machine:
      image: << parameters.img >>
    resource_class: medium
    steps:
      - run:
          name: test sudo
          command: |
            # for Ubuntu 20.04, there is the warning printed:
            #  sudo: /etc/sudoers.d/circleci:3 unknown defaults entry "rlimit_core"
            # However, it does not cause any specific error; the command ran fine.
            sudo apt update

workflows:
  jan-19-2024:
    jobs:
      - test-sudo:
          matrix:
            parameters:
              img:
                - ubuntu-2004:2024.01.1
                - ubuntu-2204:2024.01.1
