version: 2.1

jobs:
  test-path:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - run:
          command: |
            wget https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64.tar.gz -O - | tar xz && mv yq_linux_amd64 ~/bin/yq
            pwd
            echo "---------------"
            ls -laH $HOME/bin
            
            PATH=$HOME/bin:$PATH
            echo "export PATH=$PATH" >> $BASH_ENV
      - run:
          command: printenv PATH
  build:
    parameters:
      img:
        type: string
    machine:
      image: << parameters.img >>
    resource_class: medium
    steps:
      - run: |
          docker info
      - run: |
          docker-compose version
      - run: |
          uname -r
 
workflows:
  main:
    jobs:
      - test-path
      - build:
          matrix:
            parameters:
              img:
                # try again
                - "ubuntu-2204:2022.04.1"
#                 - "circleci/classic:201710-01"
#                 - "ubuntu-2004:202111-02"
#                 - "ubuntu-2004:202201-02"

