# this is a minimal config for Development branch.
# we do not want any workflows to run for this branch.

version: 2.1

jobs:
  should-not-run:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          echo "should not have run" && exit 1

workflows:
  noop:
    when:
      not:
        equal: [Development, << pipeline.git.branch >>]
    jobs:
      - should-not-run
