version: 2.1

commands:
  inspect:
    steps:
      - run: lsb_release -a
      - run: cat /proc/sys/fs/inotify/max_user_watches

jobs:
  inspect:
    parameters:
      img:
        type: string
    machine:
      image: << parameters.img >>
    resource_class: medium
    steps:
      - inspect

workflows:
  inspect:
    jobs:
      - inspect:
          matrix:
            parameters:
              img:
                - ubuntu-2204:2024.04.4
                - ubuntu-2204:2024.02.7
