version: 2.1

jobs:
  build_container:
    machine:
      image: "ubuntu-2004:202107-02"
      docker_layer_caching: true
    steps:
      - run: |
          docker version

workflows:
  main:
    jobs:
      - build_container
