version: 2.1

commands:
  install-openvpn:
    steps:
      - run: |
          sudo apt-get -y update
          sudo apt-get install openvpn openvpn-systemd-resolved

jobs:
  build:
    parameters:
      img:
        type: string
    machine:
      image: << parameters.img >>
    resource_class: medium
    steps:
      - install-openvpn
 
workflows:
  vpn:
    jobs:
      - build:
          matrix:
            parameters:
              img:
                - ubuntu-2204:2022.07.1
                - ubuntu-2204:2022.04.2
                - ubuntu-2204:2022.04.1

