version: 2.1

jobs:
  test-sudo:
    machine:
      image: ubuntu-2004:2024.01.1
    resource_class: medium
    steps:
      - run:
          name: test sudo
          command: |
            sudo pwd
            
 
workflows:
  jan-19-2024:
    jobs:
      - test-sudo

