version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y openvpn openvpn-systemd-resolved
