version: 2.1

jobs:
  build:
    parameters:
      img:
        type: string
    machine:
      image: << parameters.img >>
    resource_class: medium
    steps:
      - run: |
          docker info
      - run: |
          docker-compose version
      - run: |
          uname -r
 
 workflows:
   main:
     jobs:
       - build:
           matrix:
             parameters:
               img:
                 - "circleci/classic:201710-01"
                 - "ubuntu-2004:202111-02"
                 - "ubuntu-2004:202201-02"
