version: 2.1

commands:
  node-inspect:
    steps:
#       - add_ssh_keys:
#           fingerprints:
#             - "b3:1e:03:cf:29:8b:36:a6:87:09:d9:a0:62:c6:97:fd"
#       - run: |
#           ssh -V
#           ls /home/circleci/.ssh/
#       - run: |
#           cat /home/circleci/.ssh/config
#           sed 's/IdentitiesOnly no/IdentitiesOnly yes/1' /home/circleci/.ssh/config
          
#           sed 's/IdentitiesOnly no/IdentitiesOnly yes/1' /home/circleci/.ssh/config > /home/circleci/.ssh/config
#           cat /home/circleci/.ssh/config
#       - run: |
#           # check SSH config validity
#           sshd -t
      - run: |
          which node && node --version
      - run: |
          which npm && npm --version

jobs:
  node:
    parameters:
      img:
        type: string
    machine:
      image: << parameters.img >>
    resource_class: medium
    steps:
      - node-inspect
 
workflows:
  third-brownout:
    jobs:
      - node:
          matrix:
            parameters:
              img:
                # try again
                - "ubuntu-2204:2022.04.1"
                - "ubuntu-2004:2022.04.1"
#                 - "ubuntu-1604:201903-01" # should fail
#                 - "circleci/classic:201710-01" # should fail
                - "ubuntu-2004:202111-02"
                - "ubuntu-2004:202201-02"

