version: 2.1

jobs:
  default:
    machine: true
    steps:
      - run: |
          docker version
          docker info
      - run: |
          docker-compose version
      - run: |
          lsb_release -a
          uname -r
  test-path:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - run:
          command: |
            wget https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64.tar.gz -O - | tar xz && mv yq_linux_amd64 ~/bin/yq
            pwd
            echo "---------------"
            ls -laH $HOME/bin
            
            PATH=$HOME/bin:$PATH
            echo "export PATH=$PATH" >> $BASH_ENV
      - run:
          command: printenv PATH
  build:
    parameters:
      img:
        type: string
    machine:
      image: << parameters.img >>
    resource_class: medium
    steps:
      - run: |
          docker version
          docker info
      - run: |
          docker-compose version
      - run: |
          lsb_release -a
          uname -r
 
workflows:
  third-brownout:
    jobs:
      - default
      - build:
          matrix:
            parameters:
              img:
                # try again
                - "ubuntu-2204:2022.04.1"
                - "ubuntu-2004:2022.04.1"
                - "ubuntu-1604:201903-01" # should fail
                - "circleci/classic:201710-01" # should fail
#                 - "ubuntu-2004:202111-02"
#                 - "ubuntu-2004:202201-02"

